## Project 1 - WebScraper
# From https://youtu.be/51r3zPOun5g?si=MR2AjWEhBgGIDdSw
#######################################################
# To create a cloudformation Stack with AWS CLI
#aws cloudformation create-stack \
#  --stack-name my-stack \
#  --template-body file://template.yaml \
#  --parameters ParameterKey=InstanceType,ParameterValue=t2.micro \
#  --region us-east-1
#######################################################
AWSTemplateFormatVersion: "2010-09-09"
#######################################################

####
Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    Description: EC2 instance type for all systems

####
Resources:
 MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Sub "{{resolve:ssm:/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2}}"

####
Outputs:
  InstancePublicIP:
    Description: Public IP of the EC2 instance
    Value: !GetAtt MyEC2Instance.PublicIp
