AWSTemplateFormatVersion: "2010-09-09"
# TITLE: webScraper_EC2
## WebScraper Applicaiton using EC2, S3, RDS, VPC, IAM, and CLOUDWATCH
# From https://youtu.be/51r3zPOun5g?si=MR2AjWEhBgGIDdSw
# Validate stack template:
# aws cloudformation validate-template --template-body file:///mnt/c/Users/Joasia/Documents/MikeStuff/CloudFormationProjects/cloudFormation/webScraper_EC2.yaml
# Deploy stack
# aws cloudformation create-stack   --stack-name my-stack   --template-body  file:///mnt/c/Users/Joasia/Documents/MikeStuff/CloudFormationProjects/cloudFormation/webScraper_EC2.yaml
# Delete stack
# aws cloudformation delete-stack   --stack-name my-stack
# NOTE: do not put the parameters in the cli command as theses are in the config
# NOTE: try to use a non-hardcodded Instance type
#######################################################
Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    Description: EC2 instance type for all systems
    AllowedValues:
      - t2.micro
      - t3.micro
      - t3.small
    ConstraintDescription: Must be a valid EC2 instance type (t2.micro, t3.micro, t3.small)

Rules:
  ValidateInstanceType:
    RuleCondition: !Not [!Equals [!Ref InstanceType, ""]]
    Assertions:
      - Assert:
          'Fn::Contains':
            - 
              - t2.micro
              - t3.micro
              - t3.small
            - !Ref InstanceType
        AssertDescription: Instance type must be t2.micro, t3.micro, or t3.small.


Resources:
# Web scraper server
 MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      #ImageId: ami-0c104f6f4a5d9d1d5
      ImageId: !Sub "{{resolve:ssm:/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2}}"

####
Outputs:
  InstancePublicIP:
    Description: Public IP of the EC2 instance
    Value: !GetAtt MyEC2Instance.PublicIp
