AWSTemplateFormatVersion: "2010-09-09"
# TITLE: webScraper_V1
#
# WebScraper Applicaiton using EC2, S3, RDS, VPC, IAM, will need CLOUDWATCH
# From https://youtu.be/51r3zPOun5g?si=MR2AjWEhBgGIDdSw
#
# Validate stack template:
# aws cloudformation validate-template --template-body file:///mnt/c/Users/Joasia/Documents/MikeStuff/CloudFormationProjects/cloudFormation/webScraper_V1.yaml
#
# Deploy stack
# NOTE: When using the AWS CLI to create or update a stack that includes IAM resources, you must specify the capability using the --capabilities flag
# aws cloudformation create-stack   --stack-name my-stack --template-body  file:///mnt/c/Users/Joasia/Documents/MikeStuff/CloudFormationProjects/cloudFormation/webScraper_V1.yaml --capabilities CAPABILITY_NAMED_IAM
#
# Delete stack
# aws cloudformation delete-stack   --stack-name my-stack
# NOTE: do not put the parameters in the cli command as theses are in the config
# NOTE: try to use a non-hardcodded Instance type
# NOTE: You cannot create EC2 keys as part of the build.
#######################################################
Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
      
Resources:

# Key
#  MyKeyPair:
#    Type: AWS::EC2::KeyPair
#    Properties:
#      KeyName: MyGeneratedKey
##
# Security Group for instance Connect access
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "SSH for console Connect access"
      SecurityGroupIngress:
        - IpProtocol: tcp # add -1 for all protocols
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0 # open to world non production  

# Web scraper server
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      # KeyName: !Ref MyKeyPair  # Attach the newly created key
      InstanceType: !Ref InstanceType
      #ImageId: ami-0c104f6f4a5d9d1d5
      ImageId: !Sub "{{resolve:ssm:/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2}}"
      # How to enable console Connect? A: Allow ssh in SG
      SecurityGroupIds: 
        - !Ref MySecurityGroup



# Validate stack template:
# aws cloudformation validate-template --template-body file:///mnt/c/Users/Joasia/Documents/MikeStuff/CloudFormationProjects/cloudFormation/webScraper_V2.yaml
#
# Deploy stack
# NOTE: When using the AWS CLI to create or update a stack that includes IAM resources, you must specify the capability using the --capabilities flag
# aws cloudformation create-stack   --stack-name my-stack --template-body  file:///mnt/c/Users/Joasia/Documents/MikeStuff/CloudFormationProjects/cloudFormation/webScraper_V3.yaml --capabilities CAPABILITY_NAMED_IAM  
#
# Delete stack
# aws cloudformation delete-stack   --stack-name my-stack
#
# NOTE: do not put the parameters in the cli command as theses are in the config
# NOTE: try to use a non-hardcodded Instance type
# NOTE: You cannot create EC2 keys as part of the build.
